version: '3'
#https://pspdfkit.com/blog/2018/how-to-use-docker-compose-to-run-multiple-instances-of-a-service-in-development/
services:
    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
    apache1:
        image: php:7.4-apache
        depends_on:
            - db
        ports:
            - 8888:80
        volumes:
            - ./apache1:/var/www/html/  
    # apache1:
    #     image: httpd:latest
    #     depends_on:
    #         - db
    #     ports:
    #         - "8888:80"
    #     volumes:
    #         - ./apache1://usr/local/apache2/htdocs/
    apache2:
        image: httpd:latest
        depends_on:
            - db
        ports:
            - "8889:80"
        volumes:
            - ./apache2://usr/local/apache2/htdocs/
    apache3:
        image: httpd:latest
        depends_on:
            - db
        ports:
            - "8890:80"
        volumes:
            - ./apache3://usr/local/apache2/htdocs/
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - apache1
            - apache2
            - apache3
        ports:
            - "4000:4000"